name: Update DockerHub description
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/dockerhub-description.yml'

jobs:
  update_description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thelolagemann/gminer
          short-description: ${{ github.event.repository.description }}
